name: workflow

on:
  push:
    branches:
      - main

jobs:
  my-jobs:
    name: ubuntu pe chalega
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: taiki-e/checkout-action@v1.4.2

      - name: setup node environment
        uses: actions/setup-node@v6.5.0
        with:
          cache: npm

      - name: docker image building
        run: docker build -t ${{ secrets.imagename }}:latest .

      - name: Copy schema.sql to EC2
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.ec2publicip }}
          username: ${{ secrets.ec2username }}
          key: ${{ secrets.sshkey }}
          source: "db/schema.sql"
          target: "/tmp/"

      - name: docker login
        uses: docker/login-action@v4.6.0
        with:
          username: ${{ secrets.dockerusername }}
          password: ${{ secrets.dockerpassword }}

      - name: push image to dockerhub
        run: docker push ${{ secrets.imagename }}:latest

      - name: ssh to ec2
        uses: appleboy/ssh-action@v1.2.0
        with:
          username: ${{ secrets.ec2username }}
          host: ${{ secrets.ec2publicip }}
          key: ${{ secrets.sshkey }}
          script: |
            touch sshworking
            docker exec -i mysql mysql -u root -proot test_db < /tmp/schema.sql

            docker pull ${{ secrets.imagename }}:latest

            docker stop node-app || true
            docker rm node-app || true

            docker run -d \
              -p 3000:3000 \
              --restart unless-stopped \
              --network app-network \
              -e DB_HOST=mysql -e DB_USER=root -e DB_PASSWORD=root -e DB_NAME=test_db \
              --name node-app \
              ${{ secrets.imagename }}:latest

            docker image prune -f
